### ISSUE TITLE
fre catalog build requires API update

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/fre-cli#149]
**Describe the bug**
Recent updates in CatalogBuilder,

https://github.com/NOAA-GFDL/CatalogBuilder/pull/29/files

require small updates to the fre-cli code.

**To Reproduce**
run `fre catalog build` on any pp directory

**Expected behavior**

**Additional context**

**Comment by ceblanton** [comment]
@aradhakrishnanGFDL fyi

**Comment by ilaflott** [comment]
I'm confused, the `click` API looks identical. This PR was closed, not merged?

**Comment by ilaflott** [comment]
mm...
```
(fre_cli) an010: fre-cli $] fre catalog builder /archive/Ian.Laflotte/fre/FMS2023.04_om5_20240410/ESM4.2JpiC_om5b04r1/gfdl.ncrc5-intel23-prod-openmp/pp
Traceback (most recent call last):
  File "/home/Ian.Laflotte/conda/envs/fre_cli/bin/fre", line 8, in <module>
    sys.exit(fre())
  File "/home/Ian.Laflotte/conda/envs/fre_cli/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/Ian.Laflotte/conda/envs/fre_cli/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/Ian.Laflotte/conda/envs/fre_cli/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/Ian.Laflotte/conda/envs/fre_cli/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/Ian.Laflotte/conda/envs/fre_cli/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Ian.Laflotte/conda/envs/fre_cli/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/Ian.Laflotte/conda/envs/fre_cli/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/Ian.Laflotte/conda/envs/fre_cli/lib/python3.9/site-packages/fre/catalog/frecatalog.py", line 29, in builder
    context.forward(gen_intake_gfdl.main)
AttributeError: module 'catalogbuilder.scripts.gen_intake_gfdl' has no attribute 'main'
(fre_cli) an010: fre-cli $]
```

**Comment by ilaflott** [comment]
another thought- this should be caught by a test.

**Comment by aradhakrishnanGFDL** [comment]
@Ciheim is on it, plan is to swap main with [create_catalog](https://github.com/NOAA-GFDL/CatalogBuilder/blob/main/catalogbuilder/scripts/gen_intake_gfdl.py#L32C5-L32C19) and troubleshoot as needed. +1 for tests. 

Examples and tests are added to catalogbuilder and docs for reference, in some shape or form. 

And, this might be the correct [PR](https://github.com/NOAA-GFDL/CatalogBuilder/pull/24) in catalogbuilder to reference.
